apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-migration-frontend
spec:
  selector:
    matchLabels:
      app: app-migration-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: app-migration-frontend
    spec:
      containers:
        - name: app-migration-frontend
          image: >-
            quay.io/rtaneja/app-migration-image-build@sha256:ffbf10cebf2e4ff0ea8bd30def65dbc51199431a3f5f4eea4b702ece0ae1c6e8
          ports:
            - containerPort: 8080
