kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app-migration-frontend
  labels:
    env: {{ .Values.appmodel.env }}
spec:
  to:
    kind: Service
    name: app-migration-frontend
    weight: 100
  port:
    targetPort: 8080