name: Build and Push Image
on: [ push ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Log in to registry.redhat.io
      uses: redhat-actions/podman-login@v1
      with:
        username: rtaneja@redhat.com
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: registry.redhat.io

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: app-migration-image-build
        tags: ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/rtaneja
        username: rtaneja
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"